#pragma once
#include <vfs/keycode.h>

static keycode s_scancode_keycode_table_boot[] = {
    SCANCODE_UNKNOWN, SCANCODE_UNKNOWN, SCANCODE_UNKNOWN, SCANCODE_UNKNOWN,
    SCANCODE_A, SCANCODE_B, SCANCODE_C, SCANCODE_D,
    SCANCODE_E, SCANCODE_F, SCANCODE_G, SCANCODE_H,
    SCANCODE_I, SCANCODE_J, SCANCODE_K, SCANCODE_L,
    SCANCODE_M, SCANCODE_N, SCANCODE_O, SCANCODE_P,
    SCANCODE_Q, SCANCODE_R, SCANCODE_S, SCANCODE_T,
    SCANCODE_U, SCANCODE_V, SCANCODE_W, SCANCODE_X,
    SCANCODE_Y, SCANCODE_Z, SCANCODE_1, SCANCODE_2,
    SCANCODE_3, SCANCODE_4, SCANCODE_5, SCANCODE_6,
    SCANCODE_7, SCANCODE_8, SCANCODE_9, SCANCODE_0,
    SCANCODE_ENTER, SCANCODE_ESC, SCANCODE_BACKSPACE, SCANCODE_TAB,
    SCANCODE_SPACE, SCANCODE_DASH, SCANCODE_EQUAL, SCANCODE_SQUARE_BRACKET_LEFT,
    SCANCODE_SQUARE_BRACKET_RIGHT, SCANCODE_BACKSLASH, SCANCODE_UNKNOWN,
    SCANCODE_SEMICOLON, SCANCODE_APOSTROPHE, SCANCODE_BACKTICK, SCANCODE_COMMA,
    SCANCODE_DOT, SCANCODE_FORWARD_SLASH, SCANCODE_UNKNOWN /* CAPS_LOCK */, SCANCODE_F1,
    SCANCODE_F2, SCANCODE_F3, SCANCODE_F4, SCANCODE_F5, SCANCODE_F6,
    SCANCODE_F7, SCANCODE_F8, SCANCODE_F9, SCANCODE_F10,
    SCANCODE_F11, SCANCODE_F12, SCANCODE_UNKNOWN, SCANCODE_UNKNOWN,
    SCANCODE_UNKNOWN, SCANCODE_INSERT, SCANCODE_HOME, SCANCODE_PGUP,
    SCANCODE_DELETE, SCANCODE_END, SCANCODE_PGDOWN, SCANCODE_RIGHT_ARROW,
    SCANCODE_LEFT_ARROW, SCANCODE_DOWN_ARROW, SCANCODE_UP_ARROW, SCANCODE_UNKNOWN,
    SCANCODE_FORWARD_SLASH, SCANCODE_STAR, SCANCODE_DASH, SCANCODE_PLUS,
    SCANCODE_ENTER, SCANCODE_1, SCANCODE_2, SCANCODE_3,
    SCANCODE_4, SCANCODE_5, SCANCODE_6, SCANCODE_7,
    SCANCODE_8, SCANCODE_9, SCANCODE_0, SCANCODE_DOT,
    SCANCODE_BACKSLASH, SCANCODE_UNKNOWN, SCANCODE_UNKNOWN, SCANCODE_EQUAL,
};

#define IS_NUMPAD(scancode) ((scancode >= 83 && scancode < 103) && scancode != 100)

#define LEFT_CTRL BIT(0)
#define LEFT_SHIFT BIT(1)
#define LEFT_ALT BIT(2)
#define LEFT_GUI BIT(3)
#define RIGHT_CTRL BIT(4)
#define RIGHT_SHIFT BIT(5)
#define RIGHT_ALT BIT(6)
#define RIGHT_GUI BIT(7)